// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: internal/testproto/circular.proto

package testproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Team struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Players       []*Player              `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Team) Reset() {
	*x = Team{}
	mi := &file_internal_testproto_circular_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testproto_circular_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_internal_testproto_circular_proto_rawDescGZIP(), []int{0}
}

func (x *Team) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Team) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Team          *Team                  `protobuf:"bytes,2,opt,name=team,proto3" json:"team,omitempty"` // Circular reference back to Team
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_internal_testproto_circular_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testproto_circular_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_internal_testproto_circular_proto_rawDescGZIP(), []int{1}
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

var File_internal_testproto_circular_proto protoreflect.FileDescriptor

const file_internal_testproto_circular_proto_rawDesc = "" +
	"\n" +
	"!internal/testproto/circular.proto\x12\x04test\"B\n" +
	"\x04Team\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\aplayers\x18\x02 \x03(\v2\f.test.PlayerR\aplayers\"<\n" +
	"\x06Player\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\x04team\x18\x02 \x01(\v2\n" +
	".test.TeamR\x04teamB-Z+infinispan.org/go-client/internal/testprotob\x06proto3"

var (
	file_internal_testproto_circular_proto_rawDescOnce sync.Once
	file_internal_testproto_circular_proto_rawDescData []byte
)

func file_internal_testproto_circular_proto_rawDescGZIP() []byte {
	file_internal_testproto_circular_proto_rawDescOnce.Do(func() {
		file_internal_testproto_circular_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_testproto_circular_proto_rawDesc), len(file_internal_testproto_circular_proto_rawDesc)))
	})
	return file_internal_testproto_circular_proto_rawDescData
}

var file_internal_testproto_circular_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_testproto_circular_proto_goTypes = []any{
	(*Team)(nil),   // 0: test.Team
	(*Player)(nil), // 1: test.Player
}
var file_internal_testproto_circular_proto_depIdxs = []int32{
	1, // 0: test.Team.players:type_name -> test.Player
	0, // 1: test.Player.team:type_name -> test.Team
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_testproto_circular_proto_init() }
func file_internal_testproto_circular_proto_init() {
	if File_internal_testproto_circular_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_testproto_circular_proto_rawDesc), len(file_internal_testproto_circular_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_testproto_circular_proto_goTypes,
		DependencyIndexes: file_internal_testproto_circular_proto_depIdxs,
		MessageInfos:      file_internal_testproto_circular_proto_msgTypes,
	}.Build()
	File_internal_testproto_circular_proto = out.File
	file_internal_testproto_circular_proto_goTypes = nil
	file_internal_testproto_circular_proto_depIdxs = nil
}
