// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: internal/testproto/complex.proto

package testproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for gender
type Gender int32

const (
	Gender_MALE   Gender = 0
	Gender_FEMALE Gender = 1
	Gender_OTHER  Gender = 2
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "MALE",
		1: "FEMALE",
		2: "OTHER",
	}
	Gender_value = map[string]int32{
		"MALE":   0,
		"FEMALE": 1,
		"OTHER":  2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_testproto_complex_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_internal_testproto_complex_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_internal_testproto_complex_proto_rawDescGZIP(), []int{0}
}

// Enum for account type
type AccountType int32

const (
	AccountType_CHECKING   AccountType = 0
	AccountType_SAVINGS    AccountType = 1
	AccountType_INVESTMENT AccountType = 2
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "CHECKING",
		1: "SAVINGS",
		2: "INVESTMENT",
	}
	AccountType_value = map[string]int32{
		"CHECKING":   0,
		"SAVINGS":    1,
		"INVESTMENT": 2,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_testproto_complex_proto_enumTypes[1].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_internal_testproto_complex_proto_enumTypes[1]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_internal_testproto_complex_proto_rawDescGZIP(), []int{1}
}

// Address message (used as nested type)
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Postcode      string                 `protobuf:"bytes,4,opt,name=postcode,proto3" json:"postcode,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_internal_testproto_complex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testproto_complex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_internal_testproto_complex_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetPostcode() string {
	if x != nil {
		return x.Postcode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

// Phone number message
type PhoneNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "mobile", "home", "work"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneNumber) Reset() {
	*x = PhoneNumber{}
	mi := &file_internal_testproto_complex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneNumber) ProtoMessage() {}

func (x *PhoneNumber) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testproto_complex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneNumber.ProtoReflect.Descriptor instead.
func (*PhoneNumber) Descriptor() ([]byte, []int) {
	return file_internal_testproto_complex_proto_rawDescGZIP(), []int{1}
}

func (x *PhoneNumber) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *PhoneNumber) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// User message with complex nested structures
// Based on ClientProtoStreamMarshallerTest.java
type User struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Surname string                 `protobuf:"bytes,3,opt,name=surname,proto3" json:"surname,omitempty"`
	Gender  Gender                 `protobuf:"varint,4,opt,name=gender,proto3,enum=test.Gender" json:"gender,omitempty"`
	// Repeated fields
	AccountIds   []int32        `protobuf:"varint,5,rep,packed,name=account_ids,json=accountIds,proto3" json:"account_ids,omitempty"`
	Addresses    []*Address     `protobuf:"bytes,6,rep,name=addresses,proto3" json:"addresses,omitempty"`
	PhoneNumbers []*PhoneNumber `protobuf:"bytes,7,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	// Map fields
	Metadata    map[string]string `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Preferences map[string]int32  `protobuf:"bytes,9,rep,name=preferences,proto3" json:"preferences,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Optional fields (proto3)
	Nickname      *string `protobuf:"bytes,10,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	Age           *int32  `protobuf:"varint,11,opt,name=age,proto3,oneof" json:"age,omitempty"`
	Email         *string `protobuf:"bytes,12,opt,name=email,proto3,oneof" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_internal_testproto_complex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testproto_complex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_internal_testproto_complex_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *User) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_MALE
}

func (x *User) GetAccountIds() []int32 {
	if x != nil {
		return x.AccountIds
	}
	return nil
}

func (x *User) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *User) GetPhoneNumbers() []*PhoneNumber {
	if x != nil {
		return x.PhoneNumbers
	}
	return nil
}

func (x *User) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *User) GetPreferences() map[string]int32 {
	if x != nil {
		return x.Preferences
	}
	return nil
}

func (x *User) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *User) GetAge() int32 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

func (x *User) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

// Company message with nested User
type Company struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Employees     []*User                `protobuf:"bytes,2,rep,name=employees,proto3" json:"employees,omitempty"`
	Headquarters  *Address               `protobuf:"bytes,3,opt,name=headquarters,proto3" json:"headquarters,omitempty"`
	Departments   map[string]string      `protobuf:"bytes,4,rep,name=departments,proto3" json:"departments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Company) Reset() {
	*x = Company{}
	mi := &file_internal_testproto_complex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testproto_complex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_internal_testproto_complex_proto_rawDescGZIP(), []int{3}
}

func (x *Company) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Company) GetEmployees() []*User {
	if x != nil {
		return x.Employees
	}
	return nil
}

func (x *Company) GetHeadquarters() *Address {
	if x != nil {
		return x.Headquarters
	}
	return nil
}

func (x *Company) GetDepartments() map[string]string {
	if x != nil {
		return x.Departments
	}
	return nil
}

// Message with oneof
type Contact struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to ContactMethod:
	//
	//	*Contact_Email
	//	*Contact_Phone
	//	*Contact_Address
	ContactMethod isContact_ContactMethod `protobuf_oneof:"contact_method"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_internal_testproto_complex_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testproto_complex_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_internal_testproto_complex_proto_rawDescGZIP(), []int{4}
}

func (x *Contact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Contact) GetContactMethod() isContact_ContactMethod {
	if x != nil {
		return x.ContactMethod
	}
	return nil
}

func (x *Contact) GetEmail() string {
	if x != nil {
		if x, ok := x.ContactMethod.(*Contact_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *Contact) GetPhone() string {
	if x != nil {
		if x, ok := x.ContactMethod.(*Contact_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

func (x *Contact) GetAddress() *Address {
	if x != nil {
		if x, ok := x.ContactMethod.(*Contact_Address); ok {
			return x.Address
		}
	}
	return nil
}

type isContact_ContactMethod interface {
	isContact_ContactMethod()
}

type Contact_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

type Contact_Phone struct {
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3,oneof"`
}

type Contact_Address struct {
	Address *Address `protobuf:"bytes,4,opt,name=address,proto3,oneof"`
}

func (*Contact_Email) isContact_ContactMethod() {}

func (*Contact_Phone) isContact_ContactMethod() {}

func (*Contact_Address) isContact_ContactMethod() {}

// Message with nested maps
type Configuration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StringValues  map[string]string      `protobuf:"bytes,2,rep,name=string_values,json=stringValues,proto3" json:"string_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IntValues     map[string]int32       `protobuf:"bytes,3,rep,name=int_values,json=intValues,proto3" json:"int_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	BoolValues    map[string]bool        `protobuf:"bytes,4,rep,name=bool_values,json=boolValues,proto3" json:"bool_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_internal_testproto_complex_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testproto_complex_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_internal_testproto_complex_proto_rawDescGZIP(), []int{5}
}

func (x *Configuration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Configuration) GetStringValues() map[string]string {
	if x != nil {
		return x.StringValues
	}
	return nil
}

func (x *Configuration) GetIntValues() map[string]int32 {
	if x != nil {
		return x.IntValues
	}
	return nil
}

func (x *Configuration) GetBoolValues() map[string]bool {
	if x != nil {
		return x.BoolValues
	}
	return nil
}

// Message with all repeated types
type Collection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strings       []string               `protobuf:"bytes,1,rep,name=strings,proto3" json:"strings,omitempty"`
	Int32S        []int32                `protobuf:"varint,2,rep,packed,name=int32s,proto3" json:"int32s,omitempty"`
	Int64S        []int64                `protobuf:"varint,3,rep,packed,name=int64s,proto3" json:"int64s,omitempty"`
	Bools         []bool                 `protobuf:"varint,4,rep,packed,name=bools,proto3" json:"bools,omitempty"`
	Doubles       []float64              `protobuf:"fixed64,5,rep,packed,name=doubles,proto3" json:"doubles,omitempty"`
	Enums         []Gender               `protobuf:"varint,6,rep,packed,name=enums,proto3,enum=test.Gender" json:"enums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collection) Reset() {
	*x = Collection{}
	mi := &file_internal_testproto_complex_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collection) ProtoMessage() {}

func (x *Collection) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testproto_complex_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collection.ProtoReflect.Descriptor instead.
func (*Collection) Descriptor() ([]byte, []int) {
	return file_internal_testproto_complex_proto_rawDescGZIP(), []int{6}
}

func (x *Collection) GetStrings() []string {
	if x != nil {
		return x.Strings
	}
	return nil
}

func (x *Collection) GetInt32S() []int32 {
	if x != nil {
		return x.Int32S
	}
	return nil
}

func (x *Collection) GetInt64S() []int64 {
	if x != nil {
		return x.Int64S
	}
	return nil
}

func (x *Collection) GetBools() []bool {
	if x != nil {
		return x.Bools
	}
	return nil
}

func (x *Collection) GetDoubles() []float64 {
	if x != nil {
		return x.Doubles
	}
	return nil
}

func (x *Collection) GetEnums() []Gender {
	if x != nil {
		return x.Enums
	}
	return nil
}

var File_internal_testproto_complex_proto protoreflect.FileDescriptor

const file_internal_testproto_complex_proto_rawDesc = "" +
	"\n" +
	" internal/testproto/complex.proto\x12\x04test\"\x81\x01\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1a\n" +
	"\bpostcode\x18\x04 \x01(\tR\bpostcode\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\"9\n" +
	"\vPhoneNumber\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\xd4\x04\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x03 \x01(\tR\asurname\x12$\n" +
	"\x06gender\x18\x04 \x01(\x0e2\f.test.GenderR\x06gender\x12\x1f\n" +
	"\vaccount_ids\x18\x05 \x03(\x05R\n" +
	"accountIds\x12+\n" +
	"\taddresses\x18\x06 \x03(\v2\r.test.AddressR\taddresses\x126\n" +
	"\rphone_numbers\x18\a \x03(\v2\x11.test.PhoneNumberR\fphoneNumbers\x124\n" +
	"\bmetadata\x18\b \x03(\v2\x18.test.User.MetadataEntryR\bmetadata\x12=\n" +
	"\vpreferences\x18\t \x03(\v2\x1b.test.User.PreferencesEntryR\vpreferences\x12\x1f\n" +
	"\bnickname\x18\n" +
	" \x01(\tH\x00R\bnickname\x88\x01\x01\x12\x15\n" +
	"\x03age\x18\v \x01(\x05H\x01R\x03age\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\f \x01(\tH\x02R\x05email\x88\x01\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10PreferencesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B\v\n" +
	"\t_nicknameB\x06\n" +
	"\x04_ageB\b\n" +
	"\x06_email\"\xfc\x01\n" +
	"\aCompany\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\temployees\x18\x02 \x03(\v2\n" +
	".test.UserR\temployees\x121\n" +
	"\fheadquarters\x18\x03 \x01(\v2\r.test.AddressR\fheadquarters\x12@\n" +
	"\vdepartments\x18\x04 \x03(\v2\x1e.test.Company.DepartmentsEntryR\vdepartments\x1a>\n" +
	"\x10DepartmentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8a\x01\n" +
	"\aContact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x12\x16\n" +
	"\x05phone\x18\x03 \x01(\tH\x00R\x05phone\x12)\n" +
	"\aaddress\x18\x04 \x01(\v2\r.test.AddressH\x00R\aaddressB\x10\n" +
	"\x0econtact_method\"\xb6\x03\n" +
	"\rConfiguration\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12J\n" +
	"\rstring_values\x18\x02 \x03(\v2%.test.Configuration.StringValuesEntryR\fstringValues\x12A\n" +
	"\n" +
	"int_values\x18\x03 \x03(\v2\".test.Configuration.IntValuesEntryR\tintValues\x12D\n" +
	"\vbool_values\x18\x04 \x03(\v2#.test.Configuration.BoolValuesEntryR\n" +
	"boolValues\x1a?\n" +
	"\x11StringValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eIntValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a=\n" +
	"\x0fBoolValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\xaa\x01\n" +
	"\n" +
	"Collection\x12\x18\n" +
	"\astrings\x18\x01 \x03(\tR\astrings\x12\x16\n" +
	"\x06int32s\x18\x02 \x03(\x05R\x06int32s\x12\x16\n" +
	"\x06int64s\x18\x03 \x03(\x03R\x06int64s\x12\x14\n" +
	"\x05bools\x18\x04 \x03(\bR\x05bools\x12\x18\n" +
	"\adoubles\x18\x05 \x03(\x01R\adoubles\x12\"\n" +
	"\x05enums\x18\x06 \x03(\x0e2\f.test.GenderR\x05enums*)\n" +
	"\x06Gender\x12\b\n" +
	"\x04MALE\x10\x00\x12\n" +
	"\n" +
	"\x06FEMALE\x10\x01\x12\t\n" +
	"\x05OTHER\x10\x02*8\n" +
	"\vAccountType\x12\f\n" +
	"\bCHECKING\x10\x00\x12\v\n" +
	"\aSAVINGS\x10\x01\x12\x0e\n" +
	"\n" +
	"INVESTMENT\x10\x02B-Z+infinispan.org/go-client/internal/testprotob\x06proto3"

var (
	file_internal_testproto_complex_proto_rawDescOnce sync.Once
	file_internal_testproto_complex_proto_rawDescData []byte
)

func file_internal_testproto_complex_proto_rawDescGZIP() []byte {
	file_internal_testproto_complex_proto_rawDescOnce.Do(func() {
		file_internal_testproto_complex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_testproto_complex_proto_rawDesc), len(file_internal_testproto_complex_proto_rawDesc)))
	})
	return file_internal_testproto_complex_proto_rawDescData
}

var file_internal_testproto_complex_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_testproto_complex_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_testproto_complex_proto_goTypes = []any{
	(Gender)(0),           // 0: test.Gender
	(AccountType)(0),      // 1: test.AccountType
	(*Address)(nil),       // 2: test.Address
	(*PhoneNumber)(nil),   // 3: test.PhoneNumber
	(*User)(nil),          // 4: test.User
	(*Company)(nil),       // 5: test.Company
	(*Contact)(nil),       // 6: test.Contact
	(*Configuration)(nil), // 7: test.Configuration
	(*Collection)(nil),    // 8: test.Collection
	nil,                   // 9: test.User.MetadataEntry
	nil,                   // 10: test.User.PreferencesEntry
	nil,                   // 11: test.Company.DepartmentsEntry
	nil,                   // 12: test.Configuration.StringValuesEntry
	nil,                   // 13: test.Configuration.IntValuesEntry
	nil,                   // 14: test.Configuration.BoolValuesEntry
}
var file_internal_testproto_complex_proto_depIdxs = []int32{
	0,  // 0: test.User.gender:type_name -> test.Gender
	2,  // 1: test.User.addresses:type_name -> test.Address
	3,  // 2: test.User.phone_numbers:type_name -> test.PhoneNumber
	9,  // 3: test.User.metadata:type_name -> test.User.MetadataEntry
	10, // 4: test.User.preferences:type_name -> test.User.PreferencesEntry
	4,  // 5: test.Company.employees:type_name -> test.User
	2,  // 6: test.Company.headquarters:type_name -> test.Address
	11, // 7: test.Company.departments:type_name -> test.Company.DepartmentsEntry
	2,  // 8: test.Contact.address:type_name -> test.Address
	12, // 9: test.Configuration.string_values:type_name -> test.Configuration.StringValuesEntry
	13, // 10: test.Configuration.int_values:type_name -> test.Configuration.IntValuesEntry
	14, // 11: test.Configuration.bool_values:type_name -> test.Configuration.BoolValuesEntry
	0,  // 12: test.Collection.enums:type_name -> test.Gender
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_internal_testproto_complex_proto_init() }
func file_internal_testproto_complex_proto_init() {
	if File_internal_testproto_complex_proto != nil {
		return
	}
	file_internal_testproto_complex_proto_msgTypes[2].OneofWrappers = []any{}
	file_internal_testproto_complex_proto_msgTypes[4].OneofWrappers = []any{
		(*Contact_Email)(nil),
		(*Contact_Phone)(nil),
		(*Contact_Address)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_testproto_complex_proto_rawDesc), len(file_internal_testproto_complex_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_testproto_complex_proto_goTypes,
		DependencyIndexes: file_internal_testproto_complex_proto_depIdxs,
		EnumInfos:         file_internal_testproto_complex_proto_enumTypes,
		MessageInfos:      file_internal_testproto_complex_proto_msgTypes,
	}.Build()
	File_internal_testproto_complex_proto = out.File
	file_internal_testproto_complex_proto_goTypes = nil
	file_internal_testproto_complex_proto_depIdxs = nil
}
