// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: internal/testproto/essay.proto

package testproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Essay message for testing large payloads
// Based on HugeProtobufMessageTest.java
type Essay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // Can hold very large strings (68MB+)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Essay) Reset() {
	*x = Essay{}
	mi := &file_internal_testproto_essay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Essay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Essay) ProtoMessage() {}

func (x *Essay) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testproto_essay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Essay.ProtoReflect.Descriptor instead.
func (*Essay) Descriptor() ([]byte, []int) {
	return file_internal_testproto_essay_proto_rawDescGZIP(), []int{0}
}

func (x *Essay) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Essay) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_internal_testproto_essay_proto protoreflect.FileDescriptor

const file_internal_testproto_essay_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/testproto/essay.proto\x12\x04test\"7\n" +
	"\x05Essay\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontentB-Z+infinispan.org/go-client/internal/testprotob\x06proto3"

var (
	file_internal_testproto_essay_proto_rawDescOnce sync.Once
	file_internal_testproto_essay_proto_rawDescData []byte
)

func file_internal_testproto_essay_proto_rawDescGZIP() []byte {
	file_internal_testproto_essay_proto_rawDescOnce.Do(func() {
		file_internal_testproto_essay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_testproto_essay_proto_rawDesc), len(file_internal_testproto_essay_proto_rawDesc)))
	})
	return file_internal_testproto_essay_proto_rawDescData
}

var file_internal_testproto_essay_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_testproto_essay_proto_goTypes = []any{
	(*Essay)(nil), // 0: test.Essay
}
var file_internal_testproto_essay_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_testproto_essay_proto_init() }
func file_internal_testproto_essay_proto_init() {
	if File_internal_testproto_essay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_testproto_essay_proto_rawDesc), len(file_internal_testproto_essay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_testproto_essay_proto_goTypes,
		DependencyIndexes: file_internal_testproto_essay_proto_depIdxs,
		MessageInfos:      file_internal_testproto_essay_proto_msgTypes,
	}.Build()
	File_internal_testproto_essay_proto = out.File
	file_internal_testproto_essay_proto_goTypes = nil
	file_internal_testproto_essay_proto_depIdxs = nil
}
